<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>

        <PackageId>DreamWalkerJK.EFCore.BulkExtensions.GaussDB</PackageId>
        <PackageVersion>10.0.1-gaussdb.1</PackageVersion>

        <Authors>borisdj, DreamWalkerJK</Authors>
        <PackageProjectUrl>https://github.com/DreamWalkerJK/EFCore.BulkExtensions</PackageProjectUrl>
        <RepositoryUrl>https://github.com/DreamWalkerJK/EFCore.BulkExtensions</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>

        <Title>DreamWalkerJK.EFCore.BulkExtensions.GaussDB</Title>
        <Description>Bulk operations for GaussDB with Entity Framework Core.</Description>
        <PackageTags>$(PackageTags) GaussDB openGauss</PackageTags>
        <PackageReleaseNotes>GaussDB support preview release 1.</PackageReleaseNotes>

        <DisableStrongNamer>true</DisableStrongNamer>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="DotNetCore.EntityFrameworkCore.GaussDB" Version="10.0.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\EFCore.BulkExtensions.Core\EFCore.BulkExtensions.Core.csproj" />
    </ItemGroup>
</Project>
